# Generated by Django 2.2.2 on 2019-06-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuenosAires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='codpos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
