# Generated by Django 2.2.2 on 2019-06-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuenosAires', '0002_auto_20190622_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='men',
            new_name='mensaje',
        ),
    ]
