# Generated by Django 2.2.2 on 2019-06-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuenosAires', '0003_auto_20190622_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
