# Generated by Django 2.2.2 on 2019-06-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuenosAires', '0004_solicitud_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
    ]
