# Generated by Django 2.2.2 on 2019-06-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuenosAires', '0005_remove_usuario_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=10),
        ),
    ]
